//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionPaperDataFirstApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ansId { get; set; }
        public Nullable<int> paperId { get; set; }
        public Nullable<int> userId { get; set; }
        public int score { get; set; }
    
        public virtual QuestionsPaper QuestionsPaper { get; set; }
        public virtual User User { get; set; }
    }
}
