//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionPaperDataFirstApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int queId { get; set; }
        public string question1 { get; set; }
        public string opt1 { get; set; }
        public string opt2 { get; set; }
        public string opt3 { get; set; }
        public string opt4 { get; set; }
        public string answer { get; set; }
        public Nullable<int> paperId { get; set; }
    
        public virtual QuestionsPaper QuestionsPaper { get; set; }
    }
}
