//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionPaperDataFirstApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionsPaper()
        {
            this.Questions = new HashSet<Question>();
            this.Answers = new HashSet<Answer>();
        }
    
        public int paperId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int noOfQuestions { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public int userId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
