//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    
    public partial class Blog
    {
        public int BLOG_ID { get; set; }
        public string BLOG_TITLE { get; set; }
        public string BLOG_CATEGORY { get; set; }
        public string BLOG_DESCRIPTION { get; set; }
        public int BLOG_RATINGS { get; set; }
        public System.DateTime BLOG_CREATED_AT { get; set; }
    }

    public class BlogContent : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
    }
}
