//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Employee
    {
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_EMAIL { get; set; }
        public long EMP_PHONE { get; set; }
        public string EMP_DEPARTMENT { get; set; }
        public string EMP_GENDER { get; set; }
        public System.DateTime EMP_DOB { get; set; }
        public decimal EMP_SALARY { get; set; }
    }

    public class EmployeeContent : DbContext
    {
        public DbSet<Employee> Employees { get; set; }
    }
}
