//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Product
    {
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DETAILS { get; set; }
        public decimal PRODUCT_PRICE { get; set; }
        public int PRODUCT_QUANTITY { get; set; }
        public System.DateTime PRODUCT_MAN_DATE { get; set; }
        public System.DateTime PRODUCT_EXP_DATE { get; set; }
        public string PRODUCT_TYPE { get; set; }
    }

    public class ProductContent : DbContext
    {
        public DbSet<Product> Products { get; set; }
    }
}
